### ISSUE TITLE
Chatper 3 - Table vs Import

### ISSUE THREAD

**Issue by tkoriginal** [battlelinegames/ArtOfWasm#5]
I'm just curious if the timings here make sense and if anyone can shed some light on the results
When I do a 4 Million loops. The results are fairly straight forward except JS import calls took much longer than JS table calls

**js_table_test time=29
js_import_test time=44
wasm_table_test time=18
wasm_import_test time=17**

when I did 24 Million (6x increase in calls) I got 
**js_table_test time=146 (5x increase)
js_import_test time=256 (5.8x increase)
wasm_table_test time=104 (5.8x increase)
wasm_import_test time=99 (5.8x increase)**

So I'm not sure if something has changed since writing of the book but JS Table calls are almost 65% faster than direct import calls and wasm/table calls are pretty identical with about a 5-6% difference. The awesome part is that its rather linear when you increase the amount of calls. The coolest part is wasm calls are 1.5-2.5x faster than JS calls in them example. 

But any food for thought with whats happening with the industry would be appreciated or any resources that you could point me to.

**Comment by battlelinegames** [comment]
I know there has been a lot of work done on optimization since I finished writing the book about a year ago.  I'm not really sure why the js table calls would be faster.  There may have been some optimization done to improve the performance when compiling C++ with Emscripten.  IIRC Emscripten uses tables heavily for class functions, and it is possible more effort has been put into optimizing Emscirpten glue code calls.  This is all just speculation on my part.

**Comment by battlelinegames** [comment]
You may want to consider joining the WebAssembly Community Group:

https://www.w3.org/community/webassembly/

There is also a Wasm discord:

https://discord.gg/Q3f2CJ5hk4

**Comment by tkoriginal** [comment]
Thank you for your reply! Really enjoying your book! It is definitely daunting how quickly thing are changing in this space.

**Comment by battlelinegames** [comment]
Happy to help, and thank you for the kind words :-)
